START TIME: Thu May 22 00:34:53 CEST 2025
Node IP: 172.28.37.156
slurmstepd: error: couldn't chdir to `/workspace': No such file or directory: going to /tmp instead
slurmstepd: error: couldn't chdir to `/workspace': No such file or directory: going to /tmp instead
2025-05-22 00:35:13,649 - root - INFO - Total RAM: 854.46 GB
2025-05-22 00:35:13,649 - root - INFO - Total RAM: 854.46 GB
2025-05-22 00:35:13,649 - root - INFO - Total RAM: 854.46 GB
2025-05-22 00:35:13,649 - root - INFO - Total RAM: 854.46 GB
2025-05-22 00:35:13,649 - root - INFO - Available RAM: 775.55 GB
2025-05-22 00:35:13,649 - root - INFO - Available RAM: 775.55 GB
2025-05-22 00:35:13,649 - root - INFO - Available RAM: 775.55 GB
2025-05-22 00:35:13,649 - root - INFO - Available RAM: 775.55 GB
2025-05-22 00:35:13,649 - root - INFO - Available per-process RAM: 193.89 GB
2025-05-22 00:35:13,649 - root - INFO - Available per-process RAM: 193.89 GB
2025-05-22 00:35:13,649 - root - INFO - Available per-process RAM: 193.89 GB
2025-05-22 00:35:13,649 - root - INFO - Available per-process RAM: 193.89 GB
2025-05-22 00:35:20,622 - root - INFO - GPU 0: NVIDIA GH200 120GB
2025-05-22 00:35:20,623 - root - INFO -   Total memory: 94.50 GB
2025-05-22 00:35:20,623 - root - INFO -   Allocated memory: 0.00 GB
2025-05-22 00:35:20,623 - root - INFO -   Cached memory: 0.00 GB
2025-05-22 00:35:20,654 - root - INFO - GPU 0: NVIDIA GH200 120GB
2025-05-22 00:35:20,654 - root - INFO -   Total memory: 94.50 GB
2025-05-22 00:35:20,654 - root - INFO -   Allocated memory: 0.00 GB
2025-05-22 00:35:20,654 - root - INFO -   Cached memory: 0.00 GB
2025-05-22 00:35:20,669 - root - INFO - GPU 0: NVIDIA GH200 120GB
2025-05-22 00:35:20,669 - root - INFO -   Total memory: 94.50 GB
2025-05-22 00:35:20,669 - root - INFO -   Allocated memory: 0.00 GB
2025-05-22 00:35:20,669 - root - INFO -   Cached memory: 0.00 GB
2025-05-22 00:35:20,670 - root - INFO - GPU 0: NVIDIA GH200 120GB
2025-05-22 00:35:20,670 - root - INFO -   Total memory: 94.50 GB
2025-05-22 00:35:20,670 - root - INFO -   Allocated memory: 0.00 GB
2025-05-22 00:35:20,670 - root - INFO -   Cached memory: 0.00 GB
Traceback (most recent call last):
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py", line 237, in <module>
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py", line 237, in <module>
        load_model_fsdp(scaling_factor=10, scaling_strategy=scaling_strategy)load_model_fsdp(scaling_factor=10, scaling_strategy=scaling_strategy)

  File "/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py", line 68, in load_model_fsdp
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py", line 68, in load_model_fsdp
    before_alloc = torch.cuda.memory_allocated(device)
    before_alloc = torch.cuda.memory_allocated(device)
                                                                                              ^^^^^^^^^^
^^
UnboundLocalErrorUnboundLocalError: : cannot access local variable 'device' where it is not associated with a valuecannot access local variable 'device' where it is not associated with a value

2025-05-22 00:35:21,165 - root - INFO - [RANK 0]Loading a model with scale=10, scaling_strategy=ScalingStrategy.ALL, config:
TransformerModelArgs(dim=2560, n_layers=80, n_heads=80, n_kv_heads=8, multiple_of=256, ffn_dim_multiplier=1.3, norm_eps=1e-05, rope_theta=500000, norm_type='rmsnorm', seq_len=4096, vocab_size=131072)
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py", line 237, in <module>
    load_model_fsdp(scaling_factor=10, scaling_strategy=scaling_strategy)
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py", line 68, in load_model_fsdp
    before_alloc = torch.cuda.memory_allocated(device)
                                               ^^^^^^
UnboundLocalError: cannot access local variable 'device' where it is not associated with a value
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py", line 237, in <module>
    load_model_fsdp(scaling_factor=10, scaling_strategy=scaling_strategy)
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py", line 68, in load_model_fsdp
    before_alloc = torch.cuda.memory_allocated(device)
                                               ^^^^^^
UnboundLocalError: cannot access local variable 'device' where it is not associated with a value
W0522 00:35:22.078000 76922 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 77260 closing signal SIGTERM
E0522 00:35:22.086000 76922 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 77259) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.6.0a0+ecf3bae40a.nv25.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/iopsstor/scratch/cscs/elyulina/lai-proj/load_model_fsdp.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-22_00:35:22
  host      : nid006981
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 77261)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-05-22_00:35:22
  host      : nid006981
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 77262)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-22_00:35:22
  host      : nid006981
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 77259)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: nid006981: task 0: Exited with exit code 1
srun: Terminating StepId=456341.0
