START TIME: Thu May 22 14:51:18 CEST 2025
slurmstepd: error: couldn't chdir to `/workspace': No such file or directory: going to /tmp instead
slurmstepd: error: couldn't chdir to `/workspace': No such file or directory: going to /tmp instead
2025-05-22 14:51:39,256 - root - INFO - Setting seed to 42
2025-05-22 14:51:39,256 - root - INFO - Experiment args: Namespace(dataset='/capstor/store/cscs/ethz/large-sc/datasets/train_data.parquet', tokenizer_name_or_path='unsloth/Mistral-Nemo-Base-2407-bnb-4bit', sequence_length=4096, batch_size=1, fused_optimizer=False, learning_rate=5e-05, lr_warmup_steps=100, training_steps=100, logging_frequency=5, profile=False, profile_step_start=10, profile_step_end=12, grad_max_norm=1, model_dtype='bf16', compile=False, scaling_factor=19, scaling_strategy=<ScalingStrategy.ALL: 'all'>, set_seed=42)
2025-05-22 14:51:39,256 - root - INFO - Setting up DataLoaders...
2025-05-22 14:51:43,913 - root - INFO - Setting up Model...
2025-05-22 14:51:43,914 - root - INFO - Loading a model with scale=19, scaling_strategy=ScalingStrategy.ALL, config:
TransformerModelArgs(dim=4864, n_layers=152, n_heads=152, n_kv_heads=8, multiple_of=256, ffn_dim_multiplier=1.3, norm_eps=1e-05, rope_theta=500000, norm_type='rmsnorm', seq_len=4096, vocab_size=131072)
2025-05-22 14:54:39,323 - root - INFO - Total model parameters: 46,322,328,320
2025-05-22 14:54:39,330 - root - INFO - Starting training!
Traceback (most recent call last):
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/train.py", line 119, in <module>
    train(args)
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/train.py", line 80, in train
    logits = model(input_ids)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/model.py", line 423, in forward
    h = layer(h, self.freqs_cis)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/model.py", line 361, in forward
    out = h + self.feed_forward(self.ffn_norm(h))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/iopsstor/scratch/cscs/elyulina/lai-proj/model.py", line 305, in forward
    return self.w2(F.silu(self.w1(x)) * self.w3(x))
                   ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 132.00 MiB. GPU 0 has a total capacity of 94.50 GiB of which 2.70 GiB is free. Including non-PyTorch memory, this process has 91.71 GiB memory in use. Of the allocated memory 90.41 GiB is allocated by PyTorch, and 618.98 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
srun: error: nid006440: task 0: Exited with exit code 1
srun: Terminating StepId=457790.0
END TIME: Thu May 22 14:54:49 CEST 2025
